"""add_avatar_url_to_users

Revision ID: 26c7aff739a2
Revises: 7f3a8b2c1d4e
Create Date: 2026-01-25 22:27:14.467783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26c7aff739a2"
down_revision: str | None = "7f3a8b2c1d4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
