// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * DocumentPutRequest
 *
 * Schema for PUT document (create or update).
 */
export type DocumentPutRequest = {
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Is Folder
     */
    is_folder?: boolean;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * DocumentRead
 *
 * Schema for reading a document.
 */
export type DocumentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Parent Id
     */
    parent_id: string | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Path
     */
    path: string;
    /**
     * Index
     */
    index: number;
    /**
     * Is Folder
     */
    is_folder: boolean;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentRevisionRead
 *
 * Schema for reading a document revision.
 */
export type DocumentRevisionRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Batch Id
     */
    batch_id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Change Type
     */
    change_type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Content
     */
    content: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * User Name
     */
    user_name?: string | null;
    /**
     * Message
     */
    message?: string | null;
};

/**
 * DocumentTreeNode
 *
 * Schema for document tree node.
 */
export type DocumentTreeNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Path
     */
    path: string;
    /**
     * Title
     */
    title: string;
    /**
     * Index
     */
    index: number;
    /**
     * Is Folder
     */
    is_folder: boolean;
    /**
     * Children
     */
    children?: Array<DocumentTreeNode>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response schema.
 */
export type HealthResponse = {
    /**
     * Status
     */
    status: string;
    /**
     * Database
     */
    database: string;
};

/**
 * LoginRequest
 *
 * Schema for login request.
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MemberRole
 *
 * Project member role enum.
 */
export type MemberRole = 'viewer' | 'editor' | 'admin';

/**
 * ProjectCreate
 *
 * Schema for creating a project.
 */
export type ProjectCreate = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    visibility?: ProjectVisibility;
    /**
     * Git Url
     */
    git_url?: string | null;
    /**
     * Git Branch
     */
    git_branch?: string | null;
    /**
     * Git Doc Root
     */
    git_doc_root?: string | null;
    /**
     * Chat Enabled
     */
    chat_enabled?: boolean;
};

/**
 * ProjectMemberCreate
 *
 * Schema for adding a project member.
 */
export type ProjectMemberCreate = {
    /**
     * User Id
     */
    user_id: string;
    role?: MemberRole;
};

/**
 * ProjectMemberRead
 *
 * Schema for reading a project member.
 */
export type ProjectMemberRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * User Id
     */
    user_id: string;
    role: MemberRole;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectMemberUpdate
 *
 * Schema for updating a project member's role.
 */
export type ProjectMemberUpdate = {
    role: MemberRole;
};

/**
 * ProjectMemberWithUserRead
 *
 * Schema for reading a project member with user details.
 */
export type ProjectMemberWithUserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * User Id
     */
    user_id: string;
    role: MemberRole;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * User Name
     */
    user_name?: string | null;
    /**
     * User Email
     */
    user_email?: string | null;
    /**
     * User Avatar Url
     */
    user_avatar_url?: string | null;
};

/**
 * ProjectRead
 *
 * Schema for reading a project.
 */
export type ProjectRead = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    visibility?: ProjectVisibility;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Git Url
     */
    git_url: string | null;
    /**
     * Git Branch
     */
    git_branch: string | null;
    /**
     * Git Doc Root
     */
    git_doc_root: string | null;
    /**
     * Chat Enabled
     */
    chat_enabled: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 *
 * Schema for updating a project.
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    visibility?: ProjectVisibility | null;
    /**
     * Git Url
     */
    git_url?: string | null;
    /**
     * Git Branch
     */
    git_branch?: string | null;
    /**
     * Git Doc Root
     */
    git_doc_root?: string | null;
    /**
     * Chat Enabled
     */
    chat_enabled?: boolean | null;
};

/**
 * ProjectVisibility
 *
 * Project visibility enum.
 */
export type ProjectVisibility = 'public' | 'private';

/**
 * RefreshTokenRequest
 *
 * Schema for token refresh request.
 */
export type RefreshTokenRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RegisterRequest
 *
 * Schema for user registration request.
 */
export type RegisterRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RevisionBatchRead
 *
 * Schema for reading a revision batch.
 */
export type RevisionBatchRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * User Id
     */
    user_id: string | null;
    /**
     * User Name
     */
    user_name?: string | null;
    /**
     * User Avatar Url
     */
    user_avatar_url?: string | null;
    /**
     * Message
     */
    message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Documents
     */
    documents?: Array<RevisionDocumentSummary>;
};

/**
 * RevisionDocumentSummary
 *
 * Summary of document change in a revision.
 */
export type RevisionDocumentSummary = {
    /**
     * Revision Id
     */
    revision_id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Change Type
     */
    change_type: string;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Document Path
     */
    document_path: string | null;
};

/**
 * TokenResponse
 *
 * Schema for token response.
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UserProfileUpdate
 *
 * Schema for user self-profile update.
 */
export type UserProfileUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Preferred Locale
     */
    preferred_locale?: string | null;
};

/**
 * UserRead
 *
 * Schema for reading a user.
 */
export type UserRead = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Auth Provider
     */
    auth_provider: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Api Limit
     */
    api_limit: number | null;
    /**
     * Preferred Locale
     */
    preferred_locale: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/register';
};

export type RegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
    /**
     * Successful Response
     */
    201: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RefreshData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type GetCurrentUserInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetCurrentUserInfoResponse = GetCurrentUserInfoResponses[keyof GetCurrentUserInfoResponses];

export type UpdateMyProfileData = {
    body: UserProfileUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateMyProfileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMyProfileError = UpdateMyProfileErrors[keyof UpdateMyProfileErrors];

export type UpdateMyProfileResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateMyProfileResponse = UpdateMyProfileResponses[keyof UpdateMyProfileResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects';
};

export type ListProjectsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * Response List Projects
     *
     * Successful Response
     */
    200: Array<ProjectRead>;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type DeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type GetProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}';
};

export type UpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type GetDocumentTreeData = {
    body?: never;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/docs';
};

export type GetDocumentTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentTreeError = GetDocumentTreeErrors[keyof GetDocumentTreeErrors];

export type GetDocumentTreeResponses = {
    /**
     * Response Get Document Tree
     *
     * Successful Response
     */
    200: Array<DocumentTreeNode>;
};

export type GetDocumentTreeResponse = GetDocumentTreeResponses[keyof GetDocumentTreeResponses];

export type GetDocumentHistoryData = {
    body?: never;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
        /**
         * Path
         *
         * Document path
         */
        path: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects/{slug}/docs/{path}/history';
};

export type GetDocumentHistoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentHistoryError = GetDocumentHistoryErrors[keyof GetDocumentHistoryErrors];

export type GetDocumentHistoryResponses = {
    /**
     * Response Get Document History
     *
     * Successful Response
     */
    200: Array<DocumentRevisionRead>;
};

export type GetDocumentHistoryResponse = GetDocumentHistoryResponses[keyof GetDocumentHistoryResponses];

export type DeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
        /**
         * Path
         *
         * Document path
         */
        path: string;
    };
    query?: {
        /**
         * Message
         */
        message?: string | null;
    };
    url: '/api/v1/projects/{slug}/docs/{path}';
};

export type DeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
        /**
         * Path
         *
         * Document path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/docs/{path}';
};

export type GetDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type PutDocumentData = {
    body: DocumentPutRequest;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
        /**
         * Path
         *
         * Document path
         */
        path: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/docs/{path}';
};

export type PutDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutDocumentError = PutDocumentErrors[keyof PutDocumentErrors];

export type PutDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type PutDocumentResponse = PutDocumentResponses[keyof PutDocumentResponses];

export type GetProjectActivityData = {
    body?: never;
    path: {
        /**
         * Slug
         *
         * Project slug
         */
        slug: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects/{slug}/activity';
};

export type GetProjectActivityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectActivityError = GetProjectActivityErrors[keyof GetProjectActivityErrors];

export type GetProjectActivityResponses = {
    /**
     * Response Get Project Activity
     *
     * Successful Response
     */
    200: Array<RevisionBatchRead>;
};

export type GetProjectActivityResponse = GetProjectActivityResponses[keyof GetProjectActivityResponses];

export type ListMembersData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/projects/{slug}/members';
};

export type ListMembersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMembersError = ListMembersErrors[keyof ListMembersErrors];

export type ListMembersResponses = {
    /**
     * Response List Members
     *
     * Successful Response
     */
    200: Array<ProjectMemberWithUserRead>;
};

export type ListMembersResponse = ListMembersResponses[keyof ListMembersResponses];

export type AddMemberData = {
    body: ProjectMemberCreate;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/members';
};

export type AddMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMemberError = AddMemberErrors[keyof AddMemberErrors];

export type AddMemberResponses = {
    /**
     * Successful Response
     */
    201: ProjectMemberRead;
};

export type AddMemberResponse = AddMemberResponses[keyof AddMemberResponses];

export type RemoveMemberData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/members/{member_id}';
};

export type RemoveMemberErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveMemberError = RemoveMemberErrors[keyof RemoveMemberErrors];

export type RemoveMemberResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoveMemberResponse = RemoveMemberResponses[keyof RemoveMemberResponses];

export type UpdateMemberRoleData = {
    body: ProjectMemberUpdate;
    path: {
        /**
         * Slug
         */
        slug: string;
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{slug}/members/{member_id}';
};

export type UpdateMemberRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMemberRoleError = UpdateMemberRoleErrors[keyof UpdateMemberRoleErrors];

export type UpdateMemberRoleResponses = {
    /**
     * Successful Response
     */
    200: ProjectMemberRead;
};

export type UpdateMemberRoleResponse = UpdateMemberRoleResponses[keyof UpdateMemberRoleResponses];
