// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 *
 * Health check response schema.
 */
export type HealthResponse = {
  /**
   * Status
   */
  status: string;
  /**
   * Database
   */
  database: string;
};

/**
 * LoginRequest
 *
 * Schema for login request.
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * RefreshTokenRequest
 *
 * Schema for token refresh request.
 */
export type RefreshTokenRequest = {
  /**
   * Refresh Token
   */
  refresh_token: string;
};

/**
 * RegisterRequest
 *
 * Schema for user registration request.
 */
export type RegisterRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * Password
   */
  password: string;
};

/**
 * TokenResponse
 *
 * Schema for token response.
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Refresh Token
   */
  refresh_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * UserRead
 *
 * Schema for reading a user.
 */
export type UserRead = {
  /**
   * Email
   */
  email: string;
  /**
   * Name
   */
  name: string;
  /**
   * Id
   */
  id: string;
  /**
   * Auth Provider
   */
  auth_provider: string;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Is Admin
   */
  is_admin: boolean;
  /**
   * Api Limit
   */
  api_limit: number | null;
  /**
   * Preferred Locale
   */
  preferred_locale: string | null;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Updated At
   */
  updated_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthCheckApiV1HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/health';
};

export type HealthCheckApiV1HealthGetResponses = {
  /**
   * Successful Response
   */
  200: HealthResponse;
};

export type HealthCheckApiV1HealthGetResponse =
  HealthCheckApiV1HealthGetResponses[keyof HealthCheckApiV1HealthGetResponses];

export type RegisterApiV1AuthRegisterPostData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/register';
};

export type RegisterApiV1AuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterApiV1AuthRegisterPostError =
  RegisterApiV1AuthRegisterPostErrors[keyof RegisterApiV1AuthRegisterPostErrors];

export type RegisterApiV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: TokenResponse;
};

export type RegisterApiV1AuthRegisterPostResponse =
  RegisterApiV1AuthRegisterPostResponses[keyof RegisterApiV1AuthRegisterPostResponses];

export type LoginApiV1AuthLoginPostData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError =
  LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginApiV1AuthLoginPostResponse =
  LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];

export type LogoutApiV1AuthLogoutPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/logout';
};

export type LogoutApiV1AuthLogoutPostResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type LogoutApiV1AuthLogoutPostResponse =
  LogoutApiV1AuthLogoutPostResponses[keyof LogoutApiV1AuthLogoutPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
  body: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError =
  RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type RefreshApiV1AuthRefreshPostResponse =
  RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
  /**
   * Successful Response
   */
  200: UserRead;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse =
  GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];
