// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * HealthResponse
 *
 * Health check response schema.
 */
export const zHealthResponse = z.object({
  status: z.string(),
  database: z.string(),
});

/**
 * LoginRequest
 *
 * Schema for login request.
 */
export const zLoginRequest = z.object({
  email: z.email(),
  password: z.string(),
});

/**
 * RefreshTokenRequest
 *
 * Schema for token refresh request.
 */
export const zRefreshTokenRequest = z.object({
  refresh_token: z.string(),
});

/**
 * RegisterRequest
 *
 * Schema for user registration request.
 */
export const zRegisterRequest = z.object({
  email: z.email(),
  name: z.string(),
  password: z.string(),
});

/**
 * TokenResponse
 *
 * Schema for token response.
 */
export const zTokenResponse = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.optional(z.string()).default('bearer'),
});

/**
 * UserRead
 *
 * Schema for reading a user.
 */
export const zUserRead = z.object({
  email: z.email(),
  name: z.string(),
  id: z.uuid(),
  auth_provider: z.string(),
  is_active: z.boolean(),
  is_admin: z.boolean(),
  api_limit: z.union([z.int(), z.null()]),
  preferred_locale: z.union([z.string(), z.null()]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export const zHealthCheckApiV1HealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zHealthCheckApiV1HealthGetResponse = zHealthResponse;

export const zRegisterApiV1AuthRegisterPostData = z.object({
  body: zRegisterRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterApiV1AuthRegisterPostResponse = zTokenResponse;

export const zLoginApiV1AuthLoginPostData = z.object({
  body: zLoginRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLoginApiV1AuthLoginPostResponse = zTokenResponse;

export const zLogoutApiV1AuthLogoutPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLogoutApiV1AuthLogoutPostResponse = z.void();

export const zRefreshApiV1AuthRefreshPostData = z.object({
  body: zRefreshTokenRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRefreshApiV1AuthRefreshPostResponse = zTokenResponse;

export const zGetCurrentUserInfoApiV1AuthMeGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetCurrentUserInfoApiV1AuthMeGetResponse = zUserRead;
