// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { Auth, Health, type Options, Projects } from '../sdk.gen';
import type { CreateProjectData, CreateProjectError, CreateProjectResponse, DeleteProjectData, DeleteProjectError, DeleteProjectResponse, GetCurrentUserInfoData, GetCurrentUserInfoResponse, GetProjectData, GetProjectError, GetProjectResponse, HealthCheckData, HealthCheckResponse, ListProjectsData, ListProjectsError, ListProjectsResponse, LoginData, LoginError, LoginResponse, LogoutData, LogoutResponse, RefreshData, RefreshError, RefreshResponse, RegisterData, RegisterError, RegisterResponse, UpdateProjectData, UpdateProjectError, UpdateProjectResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthCheckQueryKey = (options?: Options<HealthCheckData>) => createQueryKey('healthCheck', options);

/**
 * Health Check
 *
 * Health check endpoint.
 *
 * Returns the health status of the application and database connection.
 */
export const healthCheckOptions = (options?: Options<HealthCheckData>) => queryOptions<HealthCheckResponse, AxiosError<DefaultError>, HealthCheckResponse, ReturnType<typeof healthCheckQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Health.healthCheck({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthCheckQueryKey(options)
});

/**
 * Register
 *
 * Register a new user.
 *
 * Args:
 * request: Registration request containing email, name, and password.
 * auth_service: Authentication service.
 *
 * Returns:
 * Access and refresh tokens.
 *
 * Raises:
 * HTTPException: If email is already registered.
 */
export const registerMutation = (options?: Partial<Options<RegisterData>>): UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> => {
    const mutationOptions: UseMutationOptions<RegisterResponse, AxiosError<RegisterError>, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Auth.register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 *
 * Login with email and password.
 *
 * Args:
 * request: Login request containing email and password.
 * auth_service: Authentication service.
 *
 * Returns:
 * Access and refresh tokens.
 *
 * Raises:
 * HTTPException: If credentials are invalid or user is inactive.
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Auth.login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 *
 * Logout and invalidate the current access token.
 *
 * Args:
 * credentials: HTTP Bearer credentials containing the JWT token.
 * auth_service: Authentication service.
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<DefaultError>, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Auth.logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh
 *
 * Refresh access token using a refresh token.
 *
 * Args:
 * request: Refresh token request.
 * auth_service: Authentication service.
 *
 * Returns:
 * New access and refresh tokens.
 *
 * Raises:
 * HTTPException: If refresh token is invalid.
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, AxiosError<RefreshError>, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, AxiosError<RefreshError>, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Auth.refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentUserInfoQueryKey = (options?: Options<GetCurrentUserInfoData>) => createQueryKey('getCurrentUserInfo', options);

/**
 * Get Current User Info
 *
 * Get current user information.
 *
 * Args:
 * current_user: The authenticated user.
 *
 * Returns:
 * User information.
 */
export const getCurrentUserInfoOptions = (options?: Options<GetCurrentUserInfoData>) => queryOptions<GetCurrentUserInfoResponse, AxiosError<DefaultError>, GetCurrentUserInfoResponse, ReturnType<typeof getCurrentUserInfoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Auth.getCurrentUserInfo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentUserInfoQueryKey(options)
});

export const listProjectsQueryKey = (options?: Options<ListProjectsData>) => createQueryKey('listProjects', options);

/**
 * List Projects
 *
 * List all projects owned by the current user.
 *
 * Args:
 * current_user: The authenticated user.
 * project_service: Project service.
 * skip: Number of records to skip (pagination).
 * limit: Maximum number of records to return.
 *
 * Returns:
 * List of projects owned by the current user.
 */
export const listProjectsOptions = (options?: Options<ListProjectsData>) => queryOptions<ListProjectsResponse, AxiosError<ListProjectsError>, ListProjectsResponse, ReturnType<typeof listProjectsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Projects.listProjects({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listProjectsQueryKey(options)
});

/**
 * Create Project
 *
 * Create a new project.
 *
 * Args:
 * request: Project creation data.
 * current_user: The authenticated user.
 * project_service: Project service.
 *
 * Returns:
 * The created project.
 *
 * Raises:
 * HTTPException: If slug already exists.
 */
export const createProjectMutation = (options?: Partial<Options<CreateProjectData>>): UseMutationOptions<CreateProjectResponse, AxiosError<CreateProjectError>, Options<CreateProjectData>> => {
    const mutationOptions: UseMutationOptions<CreateProjectResponse, AxiosError<CreateProjectError>, Options<CreateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Projects.createProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Project
 *
 * Delete a project.
 *
 * Args:
 * slug: The project slug.
 * current_user: The authenticated user.
 * project_service: Project service.
 *
 * Raises:
 * HTTPException: If project is not found or user is not the owner.
 */
export const deleteProjectMutation = (options?: Partial<Options<DeleteProjectData>>): UseMutationOptions<DeleteProjectResponse, AxiosError<DeleteProjectError>, Options<DeleteProjectData>> => {
    const mutationOptions: UseMutationOptions<DeleteProjectResponse, AxiosError<DeleteProjectError>, Options<DeleteProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Projects.deleteProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProjectQueryKey = (options: Options<GetProjectData>) => createQueryKey('getProject', options);

/**
 * Get Project
 *
 * Get a project by slug.
 *
 * Args:
 * slug: The project slug.
 * current_user: The authenticated user.
 * project_service: Project service.
 *
 * Returns:
 * The project.
 *
 * Raises:
 * HTTPException: If project is not found or user is not the owner.
 */
export const getProjectOptions = (options: Options<GetProjectData>) => queryOptions<GetProjectResponse, AxiosError<GetProjectError>, GetProjectResponse, ReturnType<typeof getProjectQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await Projects.getProject({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProjectQueryKey(options)
});

/**
 * Update Project
 *
 * Update a project.
 *
 * Args:
 * slug: The project slug.
 * request: Project update data.
 * current_user: The authenticated user.
 * project_service: Project service.
 *
 * Returns:
 * The updated project.
 *
 * Raises:
 * HTTPException: If project is not found or user is not the owner.
 */
export const updateProjectMutation = (options?: Partial<Options<UpdateProjectData>>): UseMutationOptions<UpdateProjectResponse, AxiosError<UpdateProjectError>, Options<UpdateProjectData>> => {
    const mutationOptions: UseMutationOptions<UpdateProjectResponse, AxiosError<UpdateProjectError>, Options<UpdateProjectData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await Projects.updateProject({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
